login:
    pattern:   /login
    defaults:  { _controller: MagnetoUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

magneto_film:
    resource: "@MagnetoFilmBundle/Resources/config/routing.yml"
    prefix:   /