<?php

namespace Magneto\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
